"""Generate PROOF.bend from a Python mirror of model.bend's tables.

The generator only decides which clash lemma each case needs; `bend PROOF.bend`
re-derives every case from model.bend itself, so a wrong mirror fails the gate
instead of proving something false. Run after editing model.bend's tables:

    python3 security-policy/impact/gen_proof.py && bend security-policy/impact/PROOF.bend
"""

from pathlib import Path

FEATURES = [
    "HomeTimeline", "Mentions", "Bookmarks", "Search", "UserProfile", "Thread",
    "CliJsonl", "Auth", "HfModelPicker", "OpenRouterModels",
    "SemanticRank", "ClusterTimeline", "ClusterTopics", "MlxProbe",
]
MLX_FEATURES = {"SemanticRank", "ClusterTimeline", "ClusterTopics", "MlxProbe"}
ENDPOINTS = ["Health", "Embeddings", "Chat", "Multimodal"]
PKGS = ["Starlette", "Transformers", "Tokenizers", "Safetensors"]
USES = {
    ("SemanticRank", "Embeddings"),
    ("ClusterTimeline", "Health"),
    ("ClusterTimeline", "Embeddings"),
    ("ClusterTopics", "Chat"),
    ("MlxProbe", "Health"),
}


def touches(e: str, p: str) -> bool:
    if p == "Starlette":
        return True
    if e == "Health":
        return False
    return not (e == "Embeddings" and p == "Safetensors")


def same(e: str, p: str) -> bool:
    return not (e == "Multimodal" and p in ("Transformers", "Tokenizers"))


def hits(f: str, p: str) -> list[str]:
    return [e for e in ENDPOINTS if (f, e) in USES and touches(e, p)]


def verdict(f: str, p: str) -> str:
    used = hits(f, p)
    if not used:
        return "Unaffected"
    return "VerifiedSame" if all(same(e, p) for e in used) else "NeedsDeviceCheck"


HEADER = '''# Proofs of LAWS.bend. Each law is a finite case split over model.bend's tables:
# every case either computes to the claim ({==}) or rests on an assumption that
# cannot hold. The large split in nothing_needs_device_check is generated by
# gen_proof.py; the checker verifies every case independently of the generator.
import Base
import ./model.bend as M
import ./LAWS.bend as Laws

def exfalso(-Goal: Type, e: Empty) -> Goal:
  match e:

def true_ty(b: Bool) -> Type:
  match b:
    case True{}:
      Unit
    case False{}:
      Empty

def false_ty(b: Bool) -> Type:
  match b:
    case True{}:
      Empty
    case False{}:
      Unit

# True and False differ.
def true_is_not_false(e: {True{} == False{} : Bool}) -> Empty:
  %e : true_ty(_)
  Unit{}

def false_is_not_true(e: {False{} == True{} : Bool}) -> Empty:
  %e : false_ty(_)
  Unit{}

def flagged_ty(v: M.Verdict) -> Type:
  match v:
    case M.NeedsDeviceCheck{}:
      Empty
    case M.Unaffected{}:
      Unit
    case M.VerifiedSame{}:
      Unit

# Unaffected and VerifiedSame are not NeedsDeviceCheck.
def unaffected_clash(e: {M.Unaffected{} == M.NeedsDeviceCheck{} : M.Verdict}) -> Empty:
  %e : flagged_ty(_)
  Unit{}

def verified_clash(e: {M.VerifiedSame{} == M.NeedsDeviceCheck{} : M.Verdict}) -> Empty:
  %e : flagged_ty(_)
  Unit{}
'''


def generate() -> str:
    out = [HEADER]

    out.append("def Laws.x_features_unaffected(f, p):\n  match f:")
    for f in FEATURES:
        out.append(f"    case M.{f}{{}}:")
        if f in MLX_FEATURES:
            out.append(f"      e => exfalso({{M.verdict(M.{f}{{}}, p) == M.Unaffected{{}} : M.Verdict}}, true_is_not_false(e))")
        else:
            out.append("      e => {==}")

    out.append("\ndef Laws.nothing_needs_device_check(f, p):\n  match f p:")
    for f in FEATURES:
        for p in PKGS:
            v = verdict(f, p)
            if v == "NeedsDeviceCheck":
                raise SystemExit(f"unprovable: {f} x {p} has an exposure with no identical old-vs-new run")
            lemma = "unaffected_clash" if v == "Unaffected" else "verified_clash"
            out.append(f"    case M.{f}{{}} M.{p}{{}}:")
            out.append(f"      e => {lemma}(e)")

    out.append("\ndef Laws.starlette_verified_for_mlx_features(f):\n  match f:")
    for f in FEATURES:
        out.append(f"    case M.{f}{{}}:")
        if f in MLX_FEATURES:
            out.append("      e => {==}")
        else:
            out.append(f"      e => exfalso({{M.verdict(M.{f}{{}}, M.Starlette{{}}) == M.VerifiedSame{{}} : M.Verdict}}, false_is_not_true(e))")

    out.append("\ndef Laws.probe_only_sees_starlette(p):\n  match p:")
    for p in PKGS:
        out.append(f"    case M.{p}{{}}:")
        if p == "Starlette":
            out.append("      differs => exfalso({M.verdict(M.MlxProbe{}, M.Starlette{}) == M.Unaffected{} : M.Verdict}, differs({==}))")
        else:
            out.append("      differs => {==}")

    out.append("\ndef Laws.safetensors_only_through_chat(f):\n  match f:")
    for f in FEATURES:
        out.append(f"    case M.{f}{{}}:")
        if hits(f, "Safetensors"):
            out.append("      e => {==}")
        else:
            out.append(f"      e => exfalso({{M.uses(M.{f}{{}}, M.Chat{{}}) == True{{}} : Bool}}, false_is_not_true(e))")

    out.append("\ndef Laws.multimodal_unreachable(f):\n  match f:")
    for f in FEATURES:
        out.append(f"    case M.{f}{{}}:\n      {{==}}")

    out.append("\ndef Laws.multimodal_gap_recorded():\n  {==}\n\ndef Laws.gaps_are_flagged():\n  {==}\n")
    return "\n".join(out)


if __name__ == "__main__":
    Path(__file__).with_name("PROOF.bend").write_text(generate())
